# selenium自动化直播1-2。复用浏览器
# Generated by Selenium IDE
import pytest
import time
# import json
from time import sleep

import yaml
from selenium import webdriver
from selenium.webdriver.common.by import By


# from selenium.webdriver.common.action_chains import ActionChains
# from selenium.webdriver.support import expected_conditions
# from selenium.webdriver.support.wait import WebDriverWait
# from selenium.webdriver.common.keys import Keys
# from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestDemo():
    def setup_method(self, method):
        self.driver = webdriver.Chrome()
        # self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_demo(self):
        self.driver.get("https://www.baidu.com/")
        # self.driver.set_window_size(1783, 1030)
        self.driver.find_element(By.ID, "kw").send_keys("霍格沃滋测试学院")
        self.driver.find_element(By.ID, "su").click()
        # self.vars["window_handles"] = self.driver.window_handles
        time.sleep(3)
        self.driver.find_element(By.LINK_TEXT, "霍格沃兹测试学院_霍格沃兹测试学院_从入门到精通").click()
        # self.vars["win7598"] = self.wait_for_window(2000)
        time.sleep(3)


class TestWework:
    # 复用浏览器
    def test_demo(self):  # 点击这个单独运行，可以看到没有打开新的窗口，而是在debug窗口上运行
        opt = webdriver.ChromeOptions()
        # 设置debug地址
        opt.debugger_address = "127.0.0.1:9222"
        driver = webdriver.Chrome(options=opt)
        driver.implicitly_wait(5)
        # driver.get("https://www.baidu.com/")
        driver.implicitly_wait(5)
        driver.get("https://work.weixin.qq.com/wework_admin/frame")
        driver.find_element_by_id("menu_contacts").click()
        print(driver.get_cookies())
        # driver.quit()

        # 使用cookie登录（使用以上的用例打印出来复制过来用的）。以下不是浏览器复用，是重新打开新的浏览器

    def test_cookie(self):
        driver = webdriver.Chrome()
        driver.implicitly_wait(5)
        # cookie是一个列表;以下是让selenium设置cookie进行登录；设置cookie之前必须先打开目标地址，即默认的域名.work.weixin.qq.com
        # 先打开企业微信扫描登录的页面
        driver.get("https://work.weixin.qq.com/wework_admin/loginpage_wx")  # 打开扫描登录的页面
        cookies = [
            {'domain': '.work.weixin.qq.com', 'httpOnly': True, 'name': 'wwrtx.vst', 'path': '/', 'secure': False,
             'value': '0BBOJRBUciWr23OuvLT5c18b9oWDBYk1pedkkUDTN3N_abOJBELWSmdFrB2v9atnnCGDTuCwD2JagFgp2jg2Zlhf82E8jHuOV6i2yOEGMTtpPGXQjnmbMSwomOpqZ5yTsop5UxQnDjpN8LGtnnZRV3rsA_DOSwNA7nnq-Ulrc8tBM1zfJjLd3JPpSJtScUi46UwuFlNvL1Sm395D7hTiFtCEYKjWrJ_sXuXCv6wk_8nbSGqMecMPaSJ3BF9zinQlwHcZUU0AE8eTxV4fvSqacw'},
            {'domain': '.work.weixin.qq.com', 'httpOnly': False, 'name': 'wwrtx.d2st', 'path': '/', 'secure': False,
             'value': 'a401313'},
            {'domain': '.qq.com', 'expiry': 1609503655, 'httpOnly': False, 'name': '_gat', 'path': '/', 'secure': False,
             'value': '1'},
            {'domain': '.work.weixin.qq.com', 'expiry': 1609530637, 'httpOnly': True, 'name': 'ww_rtkey', 'path': '/',
             'secure': True, 'value': '5ok6q0b'},
            {'domain': '.work.weixin.qq.com', 'httpOnly': False, 'name': 'wxpay.vid', 'path': '/', 'secure': False,
             'value': '1688853802199847'},
            {'domain': '.work.weixin.qq.com', 'httpOnly': False, 'name': 'wwrtx.vid', 'path': '/', 'secure': False,
             'value': '1688853802199847'},
            {'domain': '.work.weixin.qq.com', 'httpOnly': False, 'name': 'Hm_lpvt_9364e629af24cb52acc78b43e8c9f77d',
             'path': '/', 'secure': True, 'value': '1609499854'},
            {'domain': '.work.weixin.qq.com', 'httpOnly': True, 'name': 'wwrtx.ltype', 'path': '/', 'secure': False,
             'value': '1'},
            {'domain': 'work.weixin.qq.com', 'expiry': 1609530637, 'httpOnly': True, 'name': 'ww_rtkey', 'path': '/',
             'secure': False, 'value': '5ok6q0b'},
            {'domain': '.qq.com', 'expiry': 1609590027, 'httpOnly': False, 'name': '_gid', 'path': '/', 'secure': False,
             'value': 'GA1.2.1332877611.1609499132'},
            {'domain': '.qq.com', 'expiry': 2147385600, 'httpOnly': False, 'name': 'pgv_pvid', 'path': '/',
             'secure': True, 'value': '691988601'},
            {'domain': '.work.weixin.qq.com', 'httpOnly': True, 'name': 'wwrtx.refid', 'path': '/', 'secure': True,
             'value': '2329798520301531'},
            {'domain': '.work.weixin.qq.com', 'httpOnly': True, 'name': 'wwrtx.sid', 'path': '/', 'secure': False,
             'value': 'firQglylo7A_nMjX7le-i2typSVYaADCjOAi6fx5Ot7vRoJFDwy-ME-8WIZMqw2G'},
            {'domain': '.work.weixin.qq.com', 'expiry': 1639981228, 'httpOnly': False, 'name': 'wwrtx.c_gdpr',
             'path': '/', 'secure': True, 'value': '0'},
            {'domain': '.work.weixin.qq.com', 'expiry': 1641035854, 'httpOnly': False,
             'name': 'Hm_lvt_9364e629af24cb52acc78b43e8c9f77d', 'path': '/', 'secure': True,
             'value': '1609132085,1609499131'},
            {'domain': '.work.weixin.qq.com', 'httpOnly': False, 'name': 'wxpay.corpid', 'path': '/', 'secure': False,
             'value': '1970325128230535'},
            {'domain': '.qq.com', 'expiry': 2147385600, 'httpOnly': False, 'name': 'pgv_pvi', 'path': '/',
             'secure': True, 'value': '4266610688'},
            {'domain': '.work.weixin.qq.com', 'expiry': 1612095627, 'httpOnly': False, 'name': 'wwrtx.i18n_lan',
             'path': '/', 'secure': False, 'value': 'zh'},
            {'domain': '.work.weixin.qq.com', 'httpOnly': True, 'name': 'wwrtx.ref', 'path': '/', 'secure': True,
             'value': 'direct'},
            {'domain': '.qq.com', 'expiry': 1672575627, 'httpOnly': False, 'name': '_ga', 'path': '/', 'secure': False,
             'value': 'GA1.2.1916468366.1581478129'}]

        for cookie in cookies:
            driver.add_cookie(cookie)
        driver.get("https://work.weixin.qq.com/wework_admin/frame")
        driver.find_element_by_id("menu_contacts").click()
        # print(driver.get_cookies())
        time.sleep(5)
        driver.quit()

    # 获取cookie的方法
    def test_get_cookie(self):
        opt = webdriver.ChromeOptions()
        # 设置debug地址
        opt.debugger_address = "127.0.0.1:9222"
        driver = webdriver.Chrome(options=opt)
        driver.implicitly_wait(5)
        driver.get("https://work.weixin.qq.com/wework_admin/frame#contacts")
        cookie = driver.get_cookies()
        print(cookie)
        with open("data.yaml", "w", encoding="UTF-8") as f:
            yaml.dump(cookie, f)

    # 使用序列化cookie的方法进行登录。使用cookie登录所以就不需要复用了
    def test_login(self):
        driver = webdriver.Chrome()
        driver.implicitly_wait(5)
        driver.get("https://work.weixin.qq.com/wework_admin/loginpage_wx")  # 打开扫描登录的页面
        # 读文件内容，open默认就是读
        with open("data.yaml", encoding="UTF-8") as f:
            yaml_data = yaml.safe_load(f)
            for cookie in yaml_data:
                driver.add_cookie(cookie)
        driver.get("https://work.weixin.qq.com/wework_admin/frame")  # 打开登录的页面
        time.sleep(5)
